// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ouverjherohazwadfgud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91dmVyamhlcm9oYXp3YWRmZ3VkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI3MzYzNzIsImV4cCI6MjA3ODMxMjM3Mn0.jicjCmB_flZc_H_io0-v5fVHPzgf5gkj-4wdvcRXfQk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});